# Generated by Django 3.0.8 on 2020-07-02 05:39

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import intern.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(validators=[django.core.validators.MinLengthValidator(500, message='minumum of 500 characters are necessary')])),
                ('snippet', models.TextField(max_length=256)),
                ('thumbnail_image', models.ImageField(upload_to='blog/', validators=[django.core.validators.validate_image_file_extension, intern.models.validate_file_size])),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(intern.models.get_anonymous), related_name='postx', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
